### PR TITLE
Optimize all images Fixes #9

### LINKED ISSUE #9: Change size of speakers's photos
size of speakers's photo btw 400 and 500px, so why we don't resize the images to 80px(the current size) very easy if you want to do it I can :)

image

### PR DESCRIPTION
**Pull request by kossa**
I optimized all image, except `nabil_hachicha.jpg` and `moncef_hassein-bey.jpg`, I cannot open it with photshop, I dont know why :p

### CODE REVIEW

**Comment by Moncef12** [comment]
I think because I don't like PS, so, I guess it has a full right to respond back :p

**Comment by kossa** [comment]
@Moncef12 why ? :p

**Comment by kossa** [comment]
@hlagrid  thanks for Merging :)

**Comment by Moncef12** [comment]
@kossa : just a personal preference, though, PS is a great tool :)

**Comment by kossa** [comment]
Ok I see :)

**Pull request merged**
