### PR TITLE
Change Background of slider

### PR DESCRIPTION
**Pull request by kossa**
I dislike to see the slider, it's very ugly (-_-), I'm not a designer, but try this, so much better ;)

image

### CODE REVIEW

**Comment by ahsio** [comment]
@kossa I do not agree with the flat colors you used. There's too much colors used and we should keep the website simple and get a max 3-colors graphical chart. With more than 3 colors used in the whole website the design looks ugly (In my opinion). We should ask the community for this kind of improvement. / cc @hlagrid

**Comment by kossa** [comment]
You don't need to ask @hlagrid bcz he merged the PR :p

I agree for you ,as I said I'm not a designer, but I think it's better then black background, like that we can wait for a great design ;)

**Comment by ahsio** [comment]
@hlagrid I'm not asking but notifying :p <b>cc</b> means in this case: "Hey @hlagrid, you also checked this PR, here's a review I want to share with @kossa about what he did."

@algiers-meetup/contributers @algiers-meetup/owners Is there any designer who want to address this issue?

**Comment by cherifGsoul** [comment]
@kossa @ahsio checkout my branch https://github.com/cherifGsoul/algiers-meetup.github.io/tree/cherif-layout can we discuss this layout??

**Comment by kossa** [comment]
@cherifGsoul Susy, no ?

**Comment by cherifGsoul** [comment]
@kossa oui

**Pull request merged**
